const produtos = [
  {
    id: 1,
    nome: "Bolo prestígio(fatia)",
    preco: 4,
    secao: "Bolos",
    categoria: "bolo",
    img: "./src/img/boloprestigio.jpg",
    descricao: ["Bolo de massa e cobertura de chocolate e recheado com coco"],
    quantidade: 1,
  },
  {
    id: 2,
    nome: "Cupcake",
    preco: 4,
    secao: "Bolos",
    categoria: "bolo",
    img: "./src/img/cupcake.jpg",
    descricao: ["Bolinho com cobertura de Chantilly, sem recheio"],
    quantidade: 1,
  },
  {
    id: 3,
    nome: "Brownie de Nescau ©",
    preco: 4,
    secao: "Brownie",
    categoria: "brownie",
    img: "./src/img/brownies-nescau.jpg",
    descricao: [
      "Brownie com um dos achocolatados mais famosos como principal ingrediente!",
    ],
    quantidade: 1,
  },
  {
    id: 4,
    nome: "Brownie de Oreo  ©",
    preco: 6,
    secao: "Brownie",
    categoria: "brownie",
    img: "./src/img/brownie-oreo.jpg",
    descricao: ["Brownie com o biscoito Oreo dentro de sua massa"],
    quantidade: 1,
  },
  {
    id: 5,
    nome: "Copo da felicidade",
    preco: 7,
    secao: "Copo da felicidade",
    categoria: "copo",
    img: "./src/img/copo-da-felicidade.jpg",
    descricao: [
      "Copo com bombom, morango/uva e cremes de: chocolate, chocolate branco, doce de leite e/ou leite em pó, entre outras delícias",
    ],
    quantidade: 1,
  },
  {
    id: 6,
    nome: "Rocambole (100g)",
    preco: 5,
    secao: "Bolos",
    categoria: "bolo",
    img: "./src/img/rocambole.jpg",
    descricao: ["Bolo 'enrolado' com recheios diversos"],
    quantidade: 1,
  },
];
